@startuml
'https://plantuml.com/class-diagram

hide empty members

annotation Lucy <<Individual>> #red
annotation PaperBasedCollectible <<PaniniSoccerCard>> #red

footer "NFT Contract Extended" by cloudburo.net

annotation DigitalCollectible #red {
    name "51 Light Angel"
    piece "5 of 129"
}

package Blockchain <<Database>> {
  class LucysWallet {
     bcWalletAddress: PK
     privateWalletKey
     publicWalletKey
     cryptoCurrencyAccounts

   }
  class NFTContract {
    bcContractAddress: PK1
    tokenId: PK2
    tokenHash: FK
    tokenUri: FK
    bcOwnerWalletAddress: FK
  }

}

package DecentralizedFileStore <<Database>> {
    class NonFungibleArtefact <<JPG Image>>  {
        storageLocation = tokenHash
    }
}

LucysWallet *-- NFTContract: controls
NFTContract *- NonFungibleArtefact: tokenURI >
NFTContract .left. DigitalCollectible: representedBy <
Lucy -- DigitalCollectible: hasValueFor <
Lucy - LucysWallet: controls >
PaperBasedCollectible - Lucy: hasValueFor >
PaperBasedCollectible - Lucy: owns <
@enduml