@startuml
'https://plantuml.com/class-diagram

hide empty members

footer "Value Relationships" by cloudburo.net

annotation Lucy <<Individual>> #red
annotation PaperBasedCollectible <<PaniniSoccerCard>> #red

annotation DigitalCollectible #red {
    name "51 Light Angel"
    piece "5 of 129"
}


Lucy -- DigitalCollectible: hasValueFor <
PaperBasedCollectible - Lucy: hasValueFor >
PaperBasedCollectible - Lucy: owns <
@enduml