@startuml

node DynamicCaseMgmtVMNode1 {
    [Corporate Onboarding] as p21
}

node DynamicCaseMgmVMNode2 {
    [Individual Onboarding] as muy
}

node PresentationServiceVMNode1 {
    () cg9REST_IF as cg9if #red
    [CG9 - Partner Presentation Services] as cg9
    cg9if -- cg9
}

node PresentationServiceVMNode2 {
    () kefREST_IF as kefif #red
    [KEF - Partner Presentation Services] as kef
    kefif -- kef
}

node SagaExecutionVMNode {
    () sagaREST_IF as sagaif #red
    note right of sagaif
        Exposes on a per Saga Type a
        JSON Data Structure (versioned)
        Attribute types  can be mapped to the
        SAGA data dictionary. XSD definition which
        is an extension of the OLB XSD definition
    end note
    folder "SAGA Case App" {
        [ SAGA - ExecutionController] as saga
        note right of saga
            Will contain encapsulated BPM Model per
            Saga Type. Responsible to build up the
            canonical runtime model and enrich it with
            meta data (SAGA. May validate the Saga Interface
            model to be compliant with XSD definitions
        end note
        [ SAGA-BPM1 - "CorporateOnboardingSaga" ] as bqa1
        [ SAGA-BPM2 - "IndivdualOnboardingSaga" ] as bqa2
        [ SAGA-BPM3 - "InvestmentProductSalesSaga" ] as bqa3
        [ SAGA-Plugin - "BDOMActionExecutor"] as plug
        [ SAGA-Plugin - "ATODirectActionExecutor"] as plug1
        database sagaState
        saga --> bqa1
        saga --> bqa2
        saga --> bqa3
        saga --> plug
        saga --> plug1
     }
    sagaif -- saga
    sagaState - saga
    frame ATOLibrary as dml
    note left of dml
      read services to establish saga process context,
      dedicated service providers (e.g. OLB, DocumentBasket)
      may be connected directly via ATOLibrary based DMActions.
    end note
    plug1 --> dml
}

p21 ..> sagaif
muy ..> sagaif
cg9 ..> sagaif
kef ..> sagaif

node ActionExecutionControllerVMNode {
    () bdomREST_IF as bdomif #red
    [BDOM - BusinessDomainActionExecContr] as bdom
    note left of bdom
      Will load a list of versioned business
      domain actions delivered in versioned modules.
      And exposes a REST action executor interface.
      Can be evolved to horizontally scaling in case of rising
      complexity.
      May provide future support of sharding
      to partition along saga type collections.
    end note
    bdomif -- bdom
    folder "ATO-Library" {
        () dmjLIB_IF as dmjif
        [ATO - BuisnessDomainActionFramework] as dmj
        note left of dmj
          Domain specific actions are encapsulated in
          well defined domain module scopes. Allowing
          independent development per domain and module
          testing. Framework provides standardized Mockup
          support for automated testing.
        end note
        bdom --> dmjif
        dmjif -- dmj
        [ATO-Client-DActionsModule] as da1
        [ATO-Account-DActionsModule] as da2
        [ATO-Portfolio-DActionsModule] as da3
        [ATO-Notifiation-DActionsModule] as da4
        dmj --> da1
        dmj --> da2
        dmj --> da3
        dmj --> da4
    }
}

plug ..> bdomif

node ServiceProviderVMNode1 {
  [NotificationBusinesseServicesAPI] as ap1
}

node ServiceProviderMainframeNode {
  [ClientBusinessServicesAPI] as ap2
  [AccountBusinessServicesAPI] as ap3
  [PortfolioBusinessServicesAPI] as ap4
}

da1 ..> ap2
da2 ..> ap3
da3 ..> ap4
da4 ..> ap1




@enduml