@startuml
autonumber

footer "Wallet Signature Request" by cloudburo.net

actor user 
box "Runs on User's Browser" #LightBlue
boundary Browser as mbui #LightSkyBlue
control MetaMaskWallet as mmw #LightSkyBlue
end box
box "Runs on Web 2.0"
entity MintBaseWebsite as website #LightGrey
end box
box "Runs on Web 3.0 (Blockchain)" #LightYellow
entity MintBaseContract
end box

user -> mbui: openWebsite(url)
mbui -> website: fetchMintBaseApp(url)
user -> mbui: createNewStore()
mbui -> mmw: sendMsgToSign(msg)
mbui -> user: requestForWalletSignature
user -> mmw: login(password)
mmw -> user: askToApproveSignatureRequestForMintBase()
user -> mmw: approve()
mmw -> mmw: signMsg(privateKey, msg)
mmw -> mbui: sendSignedMsg(publicKey, msg)
mbui -> mbui: extractAndVerifyMsg(publicKey,msg):OK
mbui -> user: requestNFTStoreOpeningData

@enduml